"""baseline schema_info

Revision ID: 907937e8b608
Revises: 
Create Date: 2026-07-13 16:17:12.753845
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '907937e8b608'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SchemaInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('SchemaInfo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SchemaInfo_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SchemaInfo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SchemaInfo_key'))

    op.drop_table('SchemaInfo')
    # ### end Alembic commands ###
