"""notifications

Revision ID: e9ad8599b0ac
Revises: e5c41e7fb7e8
Create Date: 2026-07-14 08:51:00.958792
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e9ad8599b0ac'
down_revision: Union[str, None] = 'e5c41e7fb7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NotificationLog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recipientName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipientPhone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expenseId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eventType', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('providerMessageId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('errorMessage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sentAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('NotificationLog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NotificationLog_createdAt'), ['createdAt'], unique=False)
        batch_op.create_index(batch_op.f('ix_NotificationLog_eventType'), ['eventType'], unique=False)
        batch_op.create_index(batch_op.f('ix_NotificationLog_expenseId'), ['expenseId'], unique=False)
        batch_op.create_index(batch_op.f('ix_NotificationLog_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_NotificationLog_tenantId'), ['tenantId'], unique=False)

    op.create_table('NotificationPreference',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('userId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('smsEnabled', sa.Boolean(), nullable=False),
    sa.Column('kakaoEnabled', sa.Boolean(), nullable=False),
    sa.Column('webPushEnabled', sa.Boolean(), nullable=False),
    sa.Column('onSubmit', sa.Boolean(), nullable=False),
    sa.Column('onApprove', sa.Boolean(), nullable=False),
    sa.Column('onReject', sa.Boolean(), nullable=False),
    sa.Column('onPaymentComplete', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('NotificationPreference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NotificationPreference_tenantId'), ['tenantId'], unique=False)
        batch_op.create_index(batch_op.f('ix_NotificationPreference_userId'), ['userId'], unique=True)

    op.create_table('PushSubscription',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('userId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('p256dh', sa.Text(), nullable=True),
    sa.Column('auth', sa.Text(), nullable=True),
    sa.Column('userAgent', sa.Text(), nullable=True),
    sa.Column('deviceName', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('failedCount', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'endpoint', name='uq_push_user_endpoint')
    )
    with op.batch_alter_table('PushSubscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PushSubscription_isActive'), ['isActive'], unique=False)
        batch_op.create_index(batch_op.f('ix_PushSubscription_tenantId'), ['tenantId'], unique=False)
        batch_op.create_index(batch_op.f('ix_PushSubscription_userId'), ['userId'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PushSubscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PushSubscription_userId'))
        batch_op.drop_index(batch_op.f('ix_PushSubscription_tenantId'))
        batch_op.drop_index(batch_op.f('ix_PushSubscription_isActive'))

    op.drop_table('PushSubscription')
    with op.batch_alter_table('NotificationPreference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NotificationPreference_userId'))
        batch_op.drop_index(batch_op.f('ix_NotificationPreference_tenantId'))

    op.drop_table('NotificationPreference')
    with op.batch_alter_table('NotificationLog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NotificationLog_tenantId'))
        batch_op.drop_index(batch_op.f('ix_NotificationLog_status'))
        batch_op.drop_index(batch_op.f('ix_NotificationLog_expenseId'))
        batch_op.drop_index(batch_op.f('ix_NotificationLog_eventType'))
        batch_op.drop_index(batch_op.f('ix_NotificationLog_createdAt'))

    op.drop_table('NotificationLog')
    # ### end Alembic commands ###
