"""tenancy users roles

Revision ID: d82813355d19
Revises: 907937e8b608
Create Date: 2026-07-13 19:26:13.151425
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd82813355d19'
down_revision: Union[str, None] = '907937e8b608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SuperAdmin',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('SuperAdmin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SuperAdmin_email'), ['email'], unique=True)

    op.create_table('Tenant',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subdomain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customDomain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orgType', sa.String(), server_default='CHURCH', nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logoUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan', sa.String(), server_default='FREE', nullable=False),
    sa.Column('planStartAt', sa.DateTime(), nullable=True),
    sa.Column('planEndAt', sa.DateTime(), nullable=True),
    sa.Column('maxUsers', sa.Integer(), nullable=False),
    sa.Column('maxStorageMB', sa.Integer(), nullable=False),
    sa.Column('currentUsers', sa.Integer(), nullable=False),
    sa.Column('currentStorage', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('enabledModules', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('suspendedAt', sa.DateTime(), nullable=True),
    sa.Column('suspendReason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customDomain')
    )
    with op.batch_alter_table('Tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Tenant_isActive'), ['isActive'], unique=False)
        batch_op.create_index(batch_op.f('ix_Tenant_subdomain'), ['subdomain'], unique=True)

    op.create_table('Role',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stepNumber', sa.Integer(), nullable=True),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Role_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_Role_tenantId'), ['tenantId'], unique=False)

    op.create_table('User',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('userid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roleId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('phoneNumber', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('canRegisterUsers', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], ),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenantId', 'userid', name='uq_user_tenant_userid')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_User_isActive'), ['isActive'], unique=False)
        batch_op.create_index(batch_op.f('ix_User_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_User_tenantId'), ['tenantId'], unique=False)

    op.create_table('UserYearRole',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('userId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roleId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('departmentId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'year', 'departmentId', 'role', name='uq_useryearrole')
    )
    with op.batch_alter_table('UserYearRole', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_UserYearRole_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_UserYearRole_tenantId'), ['tenantId'], unique=False)
        batch_op.create_index(batch_op.f('ix_UserYearRole_userId'), ['userId'], unique=False)
        batch_op.create_index(batch_op.f('ix_UserYearRole_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserYearRole', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_UserYearRole_year'))
        batch_op.drop_index(batch_op.f('ix_UserYearRole_userId'))
        batch_op.drop_index(batch_op.f('ix_UserYearRole_tenantId'))
        batch_op.drop_index(batch_op.f('ix_UserYearRole_role'))

    op.drop_table('UserYearRole')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_tenantId'))
        batch_op.drop_index(batch_op.f('ix_User_role'))
        batch_op.drop_index(batch_op.f('ix_User_isActive'))

    op.drop_table('User')
    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Role_tenantId'))
        batch_op.drop_index(batch_op.f('ix_Role_code'))

    op.drop_table('Role')
    with op.batch_alter_table('Tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Tenant_subdomain'))
        batch_op.drop_index(batch_op.f('ix_Tenant_isActive'))

    op.drop_table('Tenant')
    with op.batch_alter_table('SuperAdmin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SuperAdmin_email'))

    op.drop_table('SuperAdmin')
    # ### end Alembic commands ###
