"""expense and approval

Revision ID: 34198875f00b
Revises: 1edc06e88e73
Create Date: 2026-07-13 21:14:58.508608
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '34198875f00b'
down_revision: Union[str, None] = '1edc06e88e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ApprovalLog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expenseId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actorName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actorEmail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actorRole', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stepNumber', sa.Integer(), nullable=True),
    sa.Column('stepName', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('previousStatus', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('newStatus', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('beforeSnapshot', sa.JSON(), nullable=True),
    sa.Column('afterSnapshot', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ApprovalLog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ApprovalLog_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_ApprovalLog_actorName'), ['actorName'], unique=False)
        batch_op.create_index(batch_op.f('ix_ApprovalLog_createdAt'), ['createdAt'], unique=False)
        batch_op.create_index(batch_op.f('ix_ApprovalLog_expenseId'), ['expenseId'], unique=False)
        batch_op.create_index(batch_op.f('ix_ApprovalLog_tenantId'), ['tenantId'], unique=False)

    op.create_table('Expense',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('userId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('committee', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expenseDate', sa.DateTime(), nullable=True),
    sa.Column('requestAmount', sa.Integer(), nullable=False),
    sa.Column('requestDate', sa.DateTime(), nullable=False),
    sa.Column('requestTeam', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('applicantName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('applicantTitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('applicantSignatureType', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('applicantSignatureData', sa.Text(), nullable=True),
    sa.Column('bankName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accountNumber', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accountHolder', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submittedAt', sa.DateTime(), nullable=True),
    sa.Column('approvedAt', sa.DateTime(), nullable=True),
    sa.Column('rejectedAt', sa.DateTime(), nullable=True),
    sa.Column('paymentStatus', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paymentCompletedAt', sa.DateTime(), nullable=True),
    sa.Column('paymentCompletedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paymentNote', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paymentHoldReason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paymentHoldAt', sa.DateTime(), nullable=True),
    sa.Column('paymentHoldBy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paymentSignatureType', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paymentSignatureData', sa.Text(), nullable=True),
    sa.Column('recurringExpenseId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Expense_applicantName'), ['applicantName'], unique=False)
        batch_op.create_index(batch_op.f('ix_Expense_committee'), ['committee'], unique=False)
        batch_op.create_index(batch_op.f('ix_Expense_createdAt'), ['createdAt'], unique=False)
        batch_op.create_index(batch_op.f('ix_Expense_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_Expense_paymentStatus'), ['paymentStatus'], unique=False)
        batch_op.create_index(batch_op.f('ix_Expense_requestDate'), ['requestDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_Expense_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_Expense_tenantId'), ['tenantId'], unique=False)
        batch_op.create_index(batch_op.f('ix_Expense_userId'), ['userId'], unique=False)

    op.create_table('ApprovalLine',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expenseId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('currentStep', sa.Integer(), nullable=False),
    sa.Column('totalSteps', sa.Integer(), nullable=False),
    sa.Column('isUrgent', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['expenseId'], ['Expense.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ApprovalLine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ApprovalLine_currentStep'), ['currentStep'], unique=False)
        batch_op.create_index(batch_op.f('ix_ApprovalLine_expenseId'), ['expenseId'], unique=True)

    op.create_table('ExpenseAttachment',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expenseId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publicId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secureUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fileName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fileSize', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['expenseId'], ['Expense.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ExpenseAttachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ExpenseAttachment_expenseId'), ['expenseId'], unique=False)
        batch_op.create_index(batch_op.f('ix_ExpenseAttachment_tenantId'), ['tenantId'], unique=False)

    op.create_table('ExpenseItem',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expenseId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budgetCategory', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budgetSubcategory', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budgetDetail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unitPrice', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['expenseId'], ['Expense.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ExpenseItem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ExpenseItem_expenseId'), ['expenseId'], unique=False)
        batch_op.create_index(batch_op.f('ix_ExpenseItem_tenantId'), ['tenantId'], unique=False)

    op.create_table('ApprovalStep',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approvalLineId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stepNumber', sa.Integer(), nullable=False),
    sa.Column('stepName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approverName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approverEmail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approverTitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delegatedTo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delegationReason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approvedAt', sa.DateTime(), nullable=True),
    sa.Column('rejectedAt', sa.DateTime(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signatureType', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signatureData', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isRequired', sa.Boolean(), nullable=False),
    sa.Column('isParallel', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approvalLineId'], ['ApprovalLine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ApprovalStep', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ApprovalStep_approvalLineId'), ['approvalLineId'], unique=False)
        batch_op.create_index(batch_op.f('ix_ApprovalStep_approverName'), ['approverName'], unique=False)
        batch_op.create_index(batch_op.f('ix_ApprovalStep_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ApprovalStep_stepNumber'), ['stepNumber'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ApprovalStep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ApprovalStep_stepNumber'))
        batch_op.drop_index(batch_op.f('ix_ApprovalStep_status'))
        batch_op.drop_index(batch_op.f('ix_ApprovalStep_approverName'))
        batch_op.drop_index(batch_op.f('ix_ApprovalStep_approvalLineId'))

    op.drop_table('ApprovalStep')
    with op.batch_alter_table('ExpenseItem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ExpenseItem_tenantId'))
        batch_op.drop_index(batch_op.f('ix_ExpenseItem_expenseId'))

    op.drop_table('ExpenseItem')
    with op.batch_alter_table('ExpenseAttachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ExpenseAttachment_tenantId'))
        batch_op.drop_index(batch_op.f('ix_ExpenseAttachment_expenseId'))

    op.drop_table('ExpenseAttachment')
    with op.batch_alter_table('ApprovalLine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ApprovalLine_expenseId'))
        batch_op.drop_index(batch_op.f('ix_ApprovalLine_currentStep'))

    op.drop_table('ApprovalLine')
    with op.batch_alter_table('Expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Expense_userId'))
        batch_op.drop_index(batch_op.f('ix_Expense_tenantId'))
        batch_op.drop_index(batch_op.f('ix_Expense_status'))
        batch_op.drop_index(batch_op.f('ix_Expense_requestDate'))
        batch_op.drop_index(batch_op.f('ix_Expense_paymentStatus'))
        batch_op.drop_index(batch_op.f('ix_Expense_department'))
        batch_op.drop_index(batch_op.f('ix_Expense_createdAt'))
        batch_op.drop_index(batch_op.f('ix_Expense_committee'))
        batch_op.drop_index(batch_op.f('ix_Expense_applicantName'))

    op.drop_table('Expense')
    with op.batch_alter_table('ApprovalLog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ApprovalLog_tenantId'))
        batch_op.drop_index(batch_op.f('ix_ApprovalLog_expenseId'))
        batch_op.drop_index(batch_op.f('ix_ApprovalLog_createdAt'))
        batch_op.drop_index(batch_op.f('ix_ApprovalLog_actorName'))
        batch_op.drop_index(batch_op.f('ix_ApprovalLog_action'))

    op.drop_table('ApprovalLog')
    # ### end Alembic commands ###
