"""budget hierarchy

Revision ID: 1edc06e88e73
Revises: d82813355d19
Create Date: 2026-07-13 20:06:55.679730
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1edc06e88e73'
down_revision: Union[str, None] = 'd82813355d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BudgetCategory',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('BudgetCategory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_BudgetCategory_isActive'), ['isActive'], unique=False)
        batch_op.create_index(batch_op.f('ix_BudgetCategory_sortOrder'), ['sortOrder'], unique=False)
        batch_op.create_index(batch_op.f('ix_BudgetCategory_tenantId'), ['tenantId'], unique=False)

    op.create_table('BudgetSubcategory',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categoryId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['BudgetCategory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoryId', 'name', name='uq_subcategory_category_name')
    )
    with op.batch_alter_table('BudgetSubcategory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_BudgetSubcategory_categoryId'), ['categoryId'], unique=False)
        batch_op.create_index(batch_op.f('ix_BudgetSubcategory_isActive'), ['isActive'], unique=False)
        batch_op.create_index(batch_op.f('ix_BudgetSubcategory_sortOrder'), ['sortOrder'], unique=False)
        batch_op.create_index(batch_op.f('ix_BudgetSubcategory_tenantId'), ['tenantId'], unique=False)

    op.create_table('BudgetDetail',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subcategoryId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accountCode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subcategoryId'], ['BudgetSubcategory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subcategoryId', 'name', name='uq_detail_subcategory_name')
    )
    with op.batch_alter_table('BudgetDetail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_BudgetDetail_isActive'), ['isActive'], unique=False)
        batch_op.create_index(batch_op.f('ix_BudgetDetail_sortOrder'), ['sortOrder'], unique=False)
        batch_op.create_index(batch_op.f('ix_BudgetDetail_subcategoryId'), ['subcategoryId'], unique=False)
        batch_op.create_index(batch_op.f('ix_BudgetDetail_tenantId'), ['tenantId'], unique=False)

    op.create_table('Committee',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('leaderId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['leaderId'], ['User.id'], ),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Committee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Committee_isActive'), ['isActive'], unique=False)
        batch_op.create_index(batch_op.f('ix_Committee_leaderId'), ['leaderId'], unique=False)
        batch_op.create_index(batch_op.f('ix_Committee_sortOrder'), ['sortOrder'], unique=False)
        batch_op.create_index(batch_op.f('ix_Committee_tenantId'), ['tenantId'], unique=False)

    op.create_table('BudgetDetailYear',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('budgetDetailId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('managerId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('budgetAmount', sa.Integer(), nullable=False),
    sa.Column('usedAmount', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['budgetDetailId'], ['BudgetDetail.id'], ),
    sa.ForeignKeyConstraint(['managerId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budgetDetailId', 'year', name='uq_detailyear_detail_year')
    )
    with op.batch_alter_table('BudgetDetailYear', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_BudgetDetailYear_budgetDetailId'), ['budgetDetailId'], unique=False)
        batch_op.create_index(batch_op.f('ix_BudgetDetailYear_isActive'), ['isActive'], unique=False)
        batch_op.create_index(batch_op.f('ix_BudgetDetailYear_managerId'), ['managerId'], unique=False)
        batch_op.create_index(batch_op.f('ix_BudgetDetailYear_tenantId'), ['tenantId'], unique=False)
        batch_op.create_index(batch_op.f('ix_BudgetDetailYear_year'), ['year'], unique=False)

    op.create_table('Department',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('committeeId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['committeeId'], ['Committee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('committeeId', 'name', name='uq_department_committee_name')
    )
    with op.batch_alter_table('Department', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Department_committeeId'), ['committeeId'], unique=False)
        batch_op.create_index(batch_op.f('ix_Department_isActive'), ['isActive'], unique=False)
        batch_op.create_index(batch_op.f('ix_Department_sortOrder'), ['sortOrder'], unique=False)
        batch_op.create_index(batch_op.f('ix_Department_tenantId'), ['tenantId'], unique=False)

    op.create_table('DepartmentBudgetDetail',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenantId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('departmentId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budgetDetailId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['budgetDetailId'], ['BudgetDetail.id'], ),
    sa.ForeignKeyConstraint(['departmentId'], ['Department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departmentId', 'budgetDetailId', name='uq_deptdetail_dept_detail')
    )
    with op.batch_alter_table('DepartmentBudgetDetail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_DepartmentBudgetDetail_budgetDetailId'), ['budgetDetailId'], unique=False)
        batch_op.create_index(batch_op.f('ix_DepartmentBudgetDetail_departmentId'), ['departmentId'], unique=False)
        batch_op.create_index(batch_op.f('ix_DepartmentBudgetDetail_tenantId'), ['tenantId'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DepartmentBudgetDetail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DepartmentBudgetDetail_tenantId'))
        batch_op.drop_index(batch_op.f('ix_DepartmentBudgetDetail_departmentId'))
        batch_op.drop_index(batch_op.f('ix_DepartmentBudgetDetail_budgetDetailId'))

    op.drop_table('DepartmentBudgetDetail')
    with op.batch_alter_table('Department', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Department_tenantId'))
        batch_op.drop_index(batch_op.f('ix_Department_sortOrder'))
        batch_op.drop_index(batch_op.f('ix_Department_isActive'))
        batch_op.drop_index(batch_op.f('ix_Department_committeeId'))

    op.drop_table('Department')
    with op.batch_alter_table('BudgetDetailYear', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_BudgetDetailYear_year'))
        batch_op.drop_index(batch_op.f('ix_BudgetDetailYear_tenantId'))
        batch_op.drop_index(batch_op.f('ix_BudgetDetailYear_managerId'))
        batch_op.drop_index(batch_op.f('ix_BudgetDetailYear_isActive'))
        batch_op.drop_index(batch_op.f('ix_BudgetDetailYear_budgetDetailId'))

    op.drop_table('BudgetDetailYear')
    with op.batch_alter_table('Committee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Committee_tenantId'))
        batch_op.drop_index(batch_op.f('ix_Committee_sortOrder'))
        batch_op.drop_index(batch_op.f('ix_Committee_leaderId'))
        batch_op.drop_index(batch_op.f('ix_Committee_isActive'))

    op.drop_table('Committee')
    with op.batch_alter_table('BudgetDetail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_BudgetDetail_tenantId'))
        batch_op.drop_index(batch_op.f('ix_BudgetDetail_subcategoryId'))
        batch_op.drop_index(batch_op.f('ix_BudgetDetail_sortOrder'))
        batch_op.drop_index(batch_op.f('ix_BudgetDetail_isActive'))

    op.drop_table('BudgetDetail')
    with op.batch_alter_table('BudgetSubcategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_BudgetSubcategory_tenantId'))
        batch_op.drop_index(batch_op.f('ix_BudgetSubcategory_sortOrder'))
        batch_op.drop_index(batch_op.f('ix_BudgetSubcategory_isActive'))
        batch_op.drop_index(batch_op.f('ix_BudgetSubcategory_categoryId'))

    op.drop_table('BudgetSubcategory')
    with op.batch_alter_table('BudgetCategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_BudgetCategory_tenantId'))
        batch_op.drop_index(batch_op.f('ix_BudgetCategory_sortOrder'))
        batch_op.drop_index(batch_op.f('ix_BudgetCategory_isActive'))

    op.drop_table('BudgetCategory')
    # ### end Alembic commands ###
