"""approval policy

Revision ID: e5c41e7fb7e8
Revises: 34198875f00b
Create Date: 2026-07-13 21:55:23.394433
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e5c41e7fb7e8"
down_revision: Union[str, None] = "34198875f00b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ApprovalPolicy",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenantId", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("isDefault", sa.Boolean(), nullable=False),
        sa.Column("isActive", sa.Boolean(), nullable=False),
        sa.Column("steps", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("collapseDuplicateApprovers", sa.Boolean(), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenantId"],
            ["Tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ApprovalPolicy", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ApprovalPolicy_isActive"), ["isActive"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ApprovalPolicy_isDefault"), ["isDefault"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ApprovalPolicy_tenantId"), ["tenantId"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ApprovalPolicy", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ApprovalPolicy_tenantId"))
        batch_op.drop_index(batch_op.f("ix_ApprovalPolicy_isDefault"))
        batch_op.drop_index(batch_op.f("ix_ApprovalPolicy_isActive"))

    op.drop_table("ApprovalPolicy")
    # ### end Alembic commands ###
